# Generated by Django 4.0.3 on 2022-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('provider', models.CharField(max_length=100)),
                ('plans', models.CharField(max_length=100)),
            ],
        ),
    ]
