# Generated by Django 4.0.3 on 2022-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='number',
            field=models.TextField(),
        ),
    ]
